Document: calculator
Title: Debian calculator Manual
Author: <insert document author here>
Abstract: This manual describes what calculator is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/calculator/calculator.sgml.gz

Format: postscript
Files: /usr/share/doc/calculator/calculator.ps.gz

Format: text
Files: /usr/share/doc/calculator/calculator.text.gz

Format: HTML
Index: /usr/share/doc/calculator/html/index.html
Files: /usr/share/doc/calculator/html/*.html
